name: Test LLVM Builder
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]
    paths:
      - 'LLVM.lock'
      - 'crates/llvm-builder/**'
      - '.github/workflows/test-llvm-builder.yml'

jobs:
  test:
    # TODO: Remove condition. Just temporary to not run this inside the PR while testing
    if: contains(github.event.pull_request.labels.*.name, 'llvm-test')
    strategy:
      matrix:
        runner: [parity-large, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Dependencies
        if: matrix.runner == 'parity-large'
        run: |
          sudo apt update && sudo apt-get install -y cmake ninja-build curl git libssl-dev pkg-config clang lld musl

      - name: Install Dependencies
        if: matrix.runner == 'macos-latest'
        run: |
          brew install ninja

      - name: Test
        run: make test-llvm-builder
        env:
          RUST_LOG: trace
